name: MacOS and Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        buildtype: ["Release", "Debug", "RelWithDebInfo"]
        os: [macos-latest, ubuntu-latest, ubuntu-18.04, ubuntu-20.04]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3.0.0
    
    - name: Setup pybind11
      run: pip install pybind11
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build and Install
      run: cmake --build ${{github.workspace}}/build --parallel --config ${{matrix.BUILD_TYPE}} --target install

    - name: Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: python test.py
